"""Initial migration.

Revision ID: e13206f94e18
Revises: 
Create Date: 2024-07-16 17:23:36.139783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13206f94e18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('task_update', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=False))

    with op.batch_alter_table('to_do_item', schema=None) as batch_op:
        batch_op.alter_column('completion_status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=1),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('to_do_item', schema=None) as batch_op:
        batch_op.alter_column('completion_status',
               existing_type=sa.String(length=1),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    with op.batch_alter_table('task_update', schema=None) as batch_op:
        batch_op.drop_column('task_id')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
